### PR TITLE
fix node environment issue and remove unnecessary condition

### PR DESCRIPTION
**Pull request by laysent**
Node environment does not have `document` by default, use `typeof document !== 'undefined'` to safely check.

### CODE REVIEW

**Comment by pakastin** [comment]
Good one, thanks! 👍

**Comment by pakastin** [comment]
I’m on mobile now, will release later..added #2 to remind me 🙂

**Comment by pakastin** [comment]
Released, thank you again! 😎

**Comment by laysent** [comment]
🙂 Thx

**Pull request merged**
